### ISSUE TITLE
Create an optimal Docker image for Docker + Nvidia GPU + CUDA + cuDNN + OpenBLAS that works on AWS

### ISSUE THREAD

**Issue by cfregly** [fluxcapacitor/pipeline#101]
https://github.com/NVIDIA/nvidia-docker
https://github.com/NVIDIA/nvidia-docker/wiki/Deploy-on-Amazon-EC2

**Comment by cfregly** [comment]
https://github.com/NVIDIA/nvidia-docker/wiki/Deploy-on-Amazon-EC2

**Comment by samjabrahams** [comment]
https://github.com/NVIDIA/nvidia-docker/wiki/Deploy-on-Amazon-EC2

**Comment by cfregly** [comment]
and possibly anaconda?  would be a good base Docker image for us (and others) to use

**Comment by samjabrahams** [comment]
I'm thinking we just create our own base Ubuntu 14.04/CUDA/cuDNN/Anaconda image and upload it to dockerhub

**Comment by cfregly** [comment]
totally

**Comment by cfregly** [comment]
Related to https://github.com/fluxcapacitor/pipeline/issues/84

**Comment by cfregly** [comment]
you can follow the patterns i've been using for the following Dockerfiles:

1) https://github.com/fluxcapacitor/pipeline/blob/master/Dockerfile
2) https://github.com/fluxcapacitor/pipeline/blob/master/myapps/serving/Dockerfile

that 2nd Dockerfile is an attempt at a smaller version of the first Dockerfile - specifically for the serving.  note that the CMD script at the end of the 2nd Dockerfile must be a long-running process (PID 1 on linux), otherwise the Docker container will die when started in -d (daemon) mode.

here are the relevant Docker RUN commands for each of the 2 Dockerfiles above:

1) https://github.com/fluxcapacitor/pipeline/wiki/Start-Docker-Environment#run-docker-container
2) https://github.com/fluxcapacitor/pipeline/wiki/Spark-ML-Model-Server#start-production-ml-serving-docker-container

**Comment by cfregly** [comment]
http://tech.marksblogg.com/tensorflow-nvidia-gtx-1080.html

**Comment by cfregly** [comment]
http://seanbe.github.io/post/deep-learning-aws/

**Comment by cfregly** [comment]
@samjabrahams:  I'm gonna take this one

**Comment by cfregly** [comment]
blacklist nouveau:  http://askubuntu.com/questions/481414/install-nvidia-driver-instead-nouveau

**Comment by cfregly** [comment]
https://www.tensorflow.org/versions/r0.10/get_started/os_setup.html#docker-installation

**Comment by cfregly** [comment]
Finally have a stable version here:  https://github.com/fluxcapacitor/pipeline/wiki/AWS-GPU-TensorFlow-Docker
