### ISSUE TITLE
Build Issue -  Unable to locate package linux-tools-3.10.0-229.14.1.el7.x86_64

### ISSUE THREAD

**Issue by Jayaradha** [fluxcapacitor/pipeline#11]
Steps to Reproduce
----------------------------
1. provision RHEL 7 instance in amazon.
2. Checkout the latest code from Git repo
3. build
After installing Oracle linux 
the build fails at

apt-get install -y linux-tools-common linux-tools-generic linux-tools-`uname -r` \

 uname-r for the instance I am using is 

3.10.0-229.14.1.el7.x86_64

Check below build error.
-------------------------------

Reading state information...
E: Unable to locate package linux-tools-3.10.0-229.14.1.el7.x86_64
E: Couldn't find any package by regex 'linux-tools-3.10.0-229.14.1.el7.x86_64'
The command '/bin/sh -c apt-get update  && apt-get install -y software-properties-common  && add-apt-repository ppa:webupd8team/java  && apt-get update  && echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections  && apt-get install -y oracle-java8-installer  && apt-get install -y oracle-java8-set-default  && apt-get install -y curl  && apt-get install -y wget  && apt-get install -y vim  && apt-get install -y linux-tools-common linux-tools-generic linux-tools-`uname -r`  && apt-get install -y nodejs  && apt-get install -y npm  && mkdir -p ~/.vim/{ftdetect,indent,syntax} && for d in ftdetect indent syntax ; do curl -o ~/.vim/$d/scala.vim \        https://raw.githubusercontent.com/derekwyatt/vim-scala/master/syntax/scala.vim; done  && cd ~  && apt-get install -y git  && apt-get install -y openssh-server  && apt-get install -y default-jdk  && apt-get install -y apache2  && apt-get install -y cmake  && git clone --depth=1 https://github.com/jrudolph/perf-map-agent  && cd perf-map-agent  && cmake .  && make  && cd ~  && git clone --depth=1 https://github.com/brendangregg/FlameGraph  && wget https://dl.bintray.com/sbt/native-packages/sbt/${SBT_VERSION}/sbt-${SBT_VERSION}.tgz  && tar xvzf sbt-${SBT_VERSION}.tgz  && rm sbt-${SBT_VERSION}.tgz  && ln -s /root/sbt/bin/sbt /usr/local/bin  && cd ~  && git clone https://github.com/fluxcapacitor/pipeline.git  && sbt clean clean-files' returned a non-zero code: 100
[ec2-user@ip-172-31-26-253 pipeline]$ whoami
ec2-user

**Comment by cfregly** [comment]
ah, gotcha.  any chance you can just use Docker on RHEL?  we do this at IBM and it works well.  we even run multiple Docker containers on RHEL - and are starting to build out a Kubernetes and Docker-based Autoscaling pipeline for Spark.

linux-tools isn't needed for anything except the myapps/tungsten sample apps that using the linux "perf" tool for profiling.

thanks!

-chris

**Comment by Jayaradha** [comment]
Thanks Chris!
Sounds good. For now deleted the Linux Tools to make it to work.

Thanks!
Jayaradha
