### ISSUE TITLE
Centralized logging for TensorBoard among multiple docker images

### ISSUE THREAD

**Issue by samjabrahams** [fluxcapacitor/pipeline#117]

**Comment by samjabrahams** [comment]
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tensorboard

**Comment by cfregly** [comment]
tensorflow + hdfs is now integrated

**Comment by cfregly** [comment]
Setup Distributed Tensorboard using HDFS

**Comment by innovia** [comment]
The issue I am facing is that each job runs and embedding are hard coded with full path inside the container  on the ProjectorConfig file, while tensorboard does not have the same full path, how HDFS will help me with this?

**Comment by cfregly** [comment]
complete.  using hdfs.

**Comment by innovia** [comment]
Can you please give a link to some example or write how you made it work?
