### ISSUE TITLE
Create TensorBoard Docker Image

### ISSUE THREAD

**Issue by samjabrahams** [fluxcapacitor/pipeline#118]
Should be able to store training data from multiple, separate TensorFlow images, as well as model checkpoints.

**Comment by cfregly** [comment]
use tensorflow + hdfs feature integrated into PipelineIO

**Comment by cfregly** [comment]
Setup Distributed Tensorboard using HDFS

**Comment by cfregly** [comment]
note:  tensorboard is now a separate project within the tensorflow repo:

https://github.com/tensorflow/tensorboard

we've updated the existing Dockerfile's that use TensorBoard, but still need to split these into separate Docker images.

**Comment by cfregly** [comment]
complete.
