### ISSUE TITLE
Missing \ in line number 137 in Dockerfile - Causing build issue.

### ISSUE THREAD

**Issue by Jayaradha** [fluxcapacitor/pipeline#12]
# ElasticSearch 
  # && wget https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/${ELASTICSEARCH_VERSION}/elasticsearch-${ELASTICSEARCH_VERSION}.tar.gz \
 && wget http://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-${ELASTICSEARCH_VERSION}.tar.gz
 && tar xvzf elasticsearch-${ELASTICSEARCH_VERSION}.tar.gz \
 && rm elasticsearch-${ELASTICSEARCH_VERSION}.tar.gz \

**Comment by cfregly** [comment]
fixed
