### ISSUE TITLE
 Error pulling image stderr: write /root/zeppelin-0.6.0-spark

### ISSUE THREAD

**Issue by existeundelta** [fluxcapacitor/pipeline#13]
9d502da0bc8e: Error pulling image (latest) from docker.io/fluxcapacitor/pipeline, ApplyLayer exit status 1 stdout:  stderr: write /root/zeppelin-0.6.0-spark-1.5.1-hadoop-2.6.0-fluxcapacitor/interpreter/spark/dep/zeppelin-spark-dependencies-0.6.0-incubating-SNAPSHOT.jar: read-only file system ubating-SNAPSHOT.jar: read-only file system 

I will try without zeppelin

**Comment by andypetrella** [comment]
I didn't checked the status (can help though), but the spark notebook is also installed.
Maybe it can be the best way to go.

**Comment by existeundelta** [comment]
It seems it was an error of the ssd
