### ISSUE TITLE
Setup distributed tensorflow demo cluster with latest tensorflow + kubernetes

### ISSUE THREAD

**Issue by cfregly** [fluxcapacitor/pipeline#132]
we should use kubernetes etcd for discovering the master, parameter servers (must have at least 2), and worker nodes

https://www.tensorflow.org/versions/r0.11/how_tos/distributed/index.html

**Comment by cfregly** [comment]
@Romits - i will create you a tensorflow distributed cluster here in a bit and send you the credentials

**Comment by cfregly** [comment]
i will setup the following DNS names:

tensorflow-master
tensorflow-ps1, tensorflow-ps2
tensorflow-worker1, tensorflow-worker2

**Comment by cfregly** [comment]
here's a link to the notebook:  https://github.com/fluxcapacitor/pipeline/blob/master/myapps/jupyter/TensorFlow/Fundamentals/Basic-Distributed-TensorFlow.ipynb

**Comment by cfregly** [comment]
we'd like to demo a comparison of single-node vs distributed training on a large dataset (ie. dogs_and_cats dataset)

at some point, the results of both tests should show up in TensorBoard - perhaps using the Amazon EFS to write the summary writer logs to a shared file system to be read by a single TensorBoard instance running on the single master.

**Comment by cfregly** [comment]
Here's a video of Fabrizio's Tensorflow Distributed talk at a recent workshop:  https://www.youtube.com/watch?v=lmYpRzQA5H4

**Comment by cfregly** [comment]
here are slides on distributed tensorflow from a recent meetup (towards the end):  http://www.slideshare.net/cfregly/advanced-spark-and-tensorflow-meetup-may-26-2016

**Comment by cfregly** [comment]
https://github.com/tobegit3hub/deep_recommend_system/tree/master/distributed

**Comment by Romits** [comment]
Thanks Chris. Currently working on the distributed TensorFlow cluster with 0.11 release.

**Comment by cfregly** [comment]
here's some relevant gists:

https://gist.githubusercontent.com/Mistobaan/29cb95e822523c44b6f3e32eed0c3259/raw/f4d9166358af81c838ffc0657aaf04c64f5963b7/sync_replica.py

https://raw.githubusercontent.com/tensorflow/tensorflow/4c50340c9d7d80366dfca4a1231de394cb1c00a2/tensorflow/tools/dist_test/python/mnist_replica.py

and some relevant scripts:

python tensorflow/tensorflow/tools/dist_test/server/grpc_tensorflow_server.py --cluster_spec=${CLUSTER_SPEC} --job_name=worker --task_id=0 --verbose=True

python tensorflow/tensorflow/tools/dist_test/server/grpc_tensorflow_server.py --cluster_spec=${CLUSTER_SPEC} --job_name=worker --task_id=0 --verbose=True

**Comment by Romits** [comment]
Distributed Tensorflow cluster is working and the model is currently training for MNIST dataset.

**Comment by cfregly** [comment]
it would be ideal to have the snippet of code specific to the worker (ie. line [43](https://github.com/Romits/BigDataScience/blob/master/Tensorflow/distrainer.py#L43) to line [108](https://github.com/Romits/BigDataScience/blob/master/Tensorflow/distrainer.py#L108)) separated out and executed using python's `execfile` or `exec` command.

be sure to pass the ENV variables into the exec command somehow.

**Comment by cfregly** [comment]
a question on OpenAI's slack channel:  "I'm wondering how distributed tensorflow works in your kubernetes environment. Is there a layer that handles creating the job, obtaining the ips of the allocated nodes, then using those to launch a distributed tensorflow job?"

@Romits ^^ This is what we're solving. ^^

**Comment by bhack** [comment]
How is organizing this Intel https://github.com/intel-analytics/BigDL?

**Comment by cfregly** [comment]
@bhack can you clarify your question?  i don't fully understand.  lemme know!

**Comment by bhack** [comment]
@cfregly Ops sorry I was on another thread. Please ignore it.. but could be interesting to see what Intel it is cooking with DL on Spark ;)

**Comment by cfregly** [comment]
Setup Distributed Tensorboard using HDFS

**Comment by cfregly** [comment]
tensorflow distributed + kubernetes from google tensorflow "ecosystem" project:  https://github.com/tensorflow/ecosystem/tree/master/kubernetes

**Comment by jlewi** [comment]
FYI myself and some folks on the K8s team have been working on improving distributed TF on K8s via a TPR.
 https://github.com/jlewi/mlkube.io/
If you think this is a promising approach and have suggestions on how to improve it please let us know. We are currently trying to get feedback from the ML, TF & K8s communities.

**Comment by cfregly** [comment]
https://stackoverflow.com/questions/41067398/task-assignment-in-tensorflow-distributed-process

**Comment by cfregly** [comment]
https://gist.github.com/yaroslavvb/ea1b1bae0a75c4aae593df7eca72d9ca

**Comment by cfregly** [comment]
co-locate PS and Workers in Placement Groups to improve network communication performance

**Comment by cfregly** [comment]
[Estimator](https://www.tensorflow.org/api_docs/python/tf/contrib/learn/Estimator), [Experiment](https://www.tensorflow.org/api_docs/python/tf/contrib/learn/Experiment), and [RunConfig](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/learn/python/learn/estimators/run_config.py):

https://github.com/tensorflow/tensor2tensor/blob/master/docs/distributed_training.md

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/learn/python/learn/estimators/run_config.py

**Comment by cfregly** [comment]
Mostly done in this repo.

Moving to Larger Effort with [PipelineAI Advanced/Enterprise Edition](http://pipeline.io/products).
