### ISSUE TITLE
Airflow-based continuous deployment and monitoring of Spark ML and Tensorflow pipelines

### ISSUE THREAD

**Issue by cfregly** [fluxcapacitor/pipeline#135]
Use Airflow to initiate and monitor continuous deployment pipelines from either github post-commit hooks or other trigger actions supported by Airflow.

Ideally, we'd integrate this into jupyter notebook using the following:

```
from IPython.display import display, HTML

html = '<iframe width=100% height=500 src="http://blahblah.com">'

display(HTML(html))
```

here is an ideal pipeline:

_User_

1) User commits code to github
2) Github webhook triggers Airflow continuous deployment pipeline
3) webhook returns link to Airflow pipeline dashboard page including pipeline status, kubernetes cluster, etc

_Airflow_

4) Airflow pulls down latest code using info from webhook params
5) Airflow creates Docker image
6) Airflow deploys Docker container (tagged with `canary`) to live Kubernetes cluster with `kubectl` behind load balancer of existing model/prediction servers

_User_

7) User decides if canary model/prediction server should be scaled up through A/B testing or other mechanism
8) Current model/prediction server is scaled down

**Comment by cfregly** [comment]
@uover82 : for now, assume the code in 1. above is [PMML](https://github.com/fluxcapacitor/prediction.ml/tree/master/pmml/data/census/census.pmml) 

committing a new `census.pmml` would trigger a build that ultimately leads to a new Docker image being created from this [Dockerfile](https://github.com/fluxcapacitor/prediction.ml/tree/master/pmml/Dockerfile)

**Comment by cfregly** [comment]
https://about.gitlab.com/2016/12/14/continuous-delivery-of-a-spring-boot-application-with-gitlab-ci-and-kubernetes/

**Comment by cfregly** [comment]
side note:  here's a script to build all of the docker images in this repo:  https://github.com/fluxcapacitor/pipeline/blob/master/build/docker-build.sh

**Comment by cfregly** [comment]
here's a demo of this in action:  http://jupyter.demo.pipeline.io/user/root/notebooks/Conferences/StartupML/Jan-20-2017/SparkMLTensorflowAI-HybridCloud-ContinuousDeployment.ipynb

**Comment by cfregly** [comment]
@uover82  i'm not closing this yet because we still need a way to build and deploy a docker image inside of a docker image - a blocker that you had mentioned a while back.

all code assets related to this effort - including the flask service - are here:  https://github.com/fluxcapacitor/pipeline/tree/master/scheduler.ml/airflow

**Comment by uover82** [comment]
got this - thanks, I remember. got docker-in-docker working by following solution at: https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci, installing docker: https://docs.docker.com/engine/installation/linux/ubuntu, and launching daemon: nohup docker daemon -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock &. May need some extras but seems to work ok. Have a look and perhaps let's talk.

**Comment by cfregly** [comment]
here's the Dockerfile - and kubernetes volume mount configuration - to allow building a Docker image from a Docker conatiner:

https://github.com/fluxcapacitor/pipeline/blob/master/scheduler.ml/airflow/Dockerfile

https://github.com/fluxcapacitor/pipeline/blob/master/scheduler.ml/airflow-rc.yaml#L33

we still need better secret-management for both github and dockerhub - or any other pipeline trigger we use.  this is documented here:  https://github.com/fluxcapacitor/pipeline/issues/181

closing this.
