### ISSUE TITLE
link on web page

### ISSUE THREAD

**Issue by stef999** [fluxcapacitor/pipeline#146]
Hi 
seems that weblinks have 404 issues 
https://github.com/fluxcapacitor/pipeline/wiki/Demo-Code-Layout
hope this help

**Comment by cfregly** [comment]
super helpful!

please try now.

Chris Fregly
Research Scientist @ PipelineIO
Founder @ Advanced Spark and TensorFlow Meetup
San Francisco - Chicago - Washington DC - London
