### ISSUE TITLE
In wiki https://github.com/fluxcapacitor/pipeline/wiki/Start-Docker-Container

### ISSUE THREAD

**Issue by existeundelta** [fluxcapacitor/pipeline#15]
In Windows:
 %USERPROFILE%\notebooks

don't work, see:
   https://github.com/docker/toolbox/issues/80

something like:
    //c/directory

worked

**Comment by cfregly** [comment]
oh, very interesting.  thanks for the tip, @existeundelta 

any interest in submitting a PR?  otherwise, I can certainly make the change.  appreciate the note.

**Comment by cfregly** [comment]
ah, i see you updated https://github.com/fluxcapacitor/pipeline/wiki/Start-Docker-Container to use //c/###pipelinedirectory###/

awesome.  thanks for the fix.  i'll make sure any code is updated, as well, and close this issue out.

-chris

**Comment by evbo** [comment]
How does "//c/directory" work? Are you actually persisting data from your local machine to your docker container? When I attempt this it simply creates the folder, but no data from my local machine is present in that docker folder.
