### ISSUE TITLE
Support DC/OS (Mesos) as an alternative to Kubernetes 

### ISSUE THREAD

**Issue by bhack** [fluxcapacitor/pipeline#150]
Do you have any plan to run this on dc/os?

Tensorflow has some integration at https://github.com/tensorflow/ecosystem/issues/25.

**Comment by cfregly** [comment]
@bhack great question!  and thanks for linking the github issues.  very helpful.

ironically, i just got off a call with the mesosphere guys.  we're looking to add DC/OS support to this [pipeline](https://github.com/fluxcapacitor/pipeline/) project as an alternative to Kubernetes.

other community members have asked, so we're working to prioritize this.

as always, if you're interested in contributing, please let us know.  as long as you're a nice person, we'd love to have you!  :)

i'm going to rename this issue to be the tracking issue for DC/OS support.

thanks again!

**Comment by bhack** [comment]
One of the open topic it is how DC/OS Mesos resources will interact with [XLA](https://www.tensorflow.org/versions/master/experimental/xla/).

**Comment by cfregly** [comment]
notes from some recent work in this area:

References

• Kubernetes-Mesos Architecture
• Kubernetes and the Mesosphere DCOS
• Kubernetes on Mesos
• Kubernetes on Mesos on Docker
• Kubernetes on DCOS
• Building Mesos/Omega-style frameworks on Kubernetes
• Peeking under the hood of Kubernetes on AWS

GitHub

• mesosphere/kubernetes-mesos
• mesosphere/dcos-kubectl

**Comment by cfregly** [comment]
tensorflow + mesos:  https://github.com/tensorflow/ecosystem/tree/master/marathon

**Comment by bhack** [comment]
We could support GPU trough universal container by now with Mesos and DC/OS 1.9.

**Comment by bhack** [comment]
https://github.com/tensorflow/ecosystem/issues/25

**Comment by cfregly** [comment]
defer for now.  re-open if needed.
