### ISSUE TITLE
Notebook Section heading reads find all (User, item) pairs without a rating

### ISSUE THREAD

**Issue by ras44** [fluxcapacitor/pipeline#186]
Hi @cfregly, I enjoyed watching your talk on pipeline.io and was playing around with the examples.  This might be trivial, but I noticed that the Zeppelin worksheet titled `Live Recs/02: User-to-Item Collaborative Filter Recs (ALS)` has a [section heading](https://github.com/fluxcapacitor/pipeline/blob/master/education.ml/pipeline/myapps/zeppelin/2AUYFSKXN/note.json#L198 ) that reads "find all (User, item) pairs without a rating"; however when working with it, the section actually returns all distinct user item pairs- not just pairs without a rating.

Similarly, the section titled `Generate Recommendations For (User, Item) Pairs Without Existing Ratings` generates recommendations for all (user,item) pairs.  The pairs that don't have any ratings across all users receive a NaN, and these are then dropped in the `Enrich the Recommendations` section  with the fragment `   .na.drop(Seq("prediction"))`

Just thought that might help to clear things up for new users like myself who are working through the code- it's been really helpful so far.  Thanks!

**Comment by cfregly** [comment]
@ras44:  thanks for reporting this!

any interest in submitting a pull request for the fix?

we can merge it in quickly.

thanks so much!

**Comment by ras44** [comment]
@cfregly sure thing- I'll submit one now.  thanks for the great tool!

**Comment by cfregly** [comment]
https://github.com/fluxcapacitor/pipeline/commit/c1b66cb30272ae5d8948dd6f3d4d8a70d6c0bc23
