### ISSUE TITLE
Example fails for empty item_ratings

### ISSUE THREAD

**Issue by ras44** [fluxcapacitor/pipeline#196]
@cfregly While testing out the example on an empty item_ratings table in Cassandra (ie. I don't load the example item-ratings-geo.csv dataset into Cassandra) I found it crashes unless I ignoring the NANs produced by the model during the Generate Recommendations step of the second  worksheet (Live Recs/02: User-to-Item Collaborative Filter Recs (ALS) ).  If I don't ignore the NANs, I'm unable to save the recommendations in reddis.  I'll submit a pull request to address this issue if that works for you!

**Comment by cfregly** [comment]
thanks again @ras44 ! 

https://github.com/fluxcapacitor/pipeline/commit/627829c6c131081d324b174fdd6fd647a786f61e
