### ISSUE TITLE
Login in Jupyter

### ISSUE THREAD

**Issue by SG87** [fluxcapacitor/pipeline#200]
I have installed docker and kubernetes on my Mac as explained in: https://github.com/fluxcapacitor/pipeline/wiki/Setup-Docker-and-Kubernetes-CLI

Afterwards I have created an azure container: https://github.com/fluxcapacitor/pipeline/wiki/Setup-Pipeline-Azure

I also configured the Kubernetes cluster and started all services: https://github.com/fluxcapacitor/pipeline/wiki/Setup-Pipeline-on-Kubernetes

When browsing to the Jupyter Ip ("jupyterip"/hub/login) I get the login screen. I have tried different values for Username and Password, but I am not able to login. Error:
```
500 : Internal Server Error
Spawner failed to start [status=1]
```

Could you advise me on the possible reason(s) triggering this error?

**Comment by uover82** [comment]
Hi,

I'd also check kubernetes dashboard, looking for errors/ issues:

https://<your-cluster-url>/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard/#/workload?namespace=default

Good luck!

John

**Comment by cfregly** [comment]
let me take a quick look.  i made some changes over the weekend, and i have an idea what may be wrong.

i'll reply soon with a response.

**Comment by cfregly** [comment]
ok, this should be fixed.  please try this again. @SG87
