### ISSUE TITLE
DNS resolving for HDFS datanode

### ISSUE THREAD

**Issue by Hronom** [fluxcapacitor/pipeline#201]
How you make resolving by hostname for HDFS datanode for example inside JupyterHUB.
I'm currently trying to add other service, but Kubernetes don't allow to resolve PODs IP by hostname.
Please help.

**Comment by cfregly** [comment]
hi there!  you can use SERVICE NAME for each serving such as `airflow` or `hdfs`.

you can get the list of SERVICE NAMES using the following `kubectl` command
```
kubectl get svc

### EXPECTED OUTPUT ###
NAME                    CLUSTER-IP       EXTERNAL-IP        PORT(S)
airflow                 100.66.51.243    a4a79896ff923...   80:30666/TCP,5000:30517/TCP,5555:30746/TCP,8793:30961/TCP                                                                                                                                                                                                                                                                                                               9d
alertmanager            None             <none>             9093/TCP,6783/TCP                                                                                                                                                                                                                                                                                                                                                       20d
alertmanager-main       100.66.46.10     <nodes>            9093:30903/TCP                                                                                                                                                                                                                                                                                                                                                          18d
gateway                 100.66.91.235    af32a1816fc84...   80:32538/TCP                                                                                                                                                                                                                                                                                                                                                            5d
grafana                 100.69.213.214   ab404fe2cf255...   80:30061/TCP                                                                                                                                                                                                                                                                                                                                                            18d
hdfs                    100.70.84.24     a12dacc5fef12...   9000:32063/TCP,80:31256/TCP
```

**Comment by Hronom** [comment]
@cfregly  hi,
my problem is that HDFS datanode has hostname of POD like `HDFS-erwh7`. So [HUE](http://gethue.com/) when retrieves datanodes from namenode try to resolve `HDFS-erwh7`. How you handle this in JupyterHUB, it's use IP address not hostname?

Sorry for this offtopic question...

**Comment by cfregly** [comment]
hmm, not exactly sure how HUE works, but inside jupyterhub, if you want to reference HDFS from PySpark, for example, you can simply to the following:

```
textFile.("hdfs://hdfs:9000/...")
```
 where `hdfs` is the service name shown above when you do `kubectl get svc`.

let me know if i'm misunderstanding your question.

**Comment by Hronom** [comment]
@cfregly thanks for your cooperation,

I'm just try to run [HUE](http://gethue.com/) to use for uploading data files through Web UI into HDFS. 
I use `hdfs` in settings of [HUE](http://gethue.com/) like you describe, but when [HUE](http://gethue.com/)  ask namenode, the namenode returns hostname of datanode and that hostname have name of POD.
Kubernetes not allow to resolve IP by DNS name of POD. So without modification of host file inside HUE container - I'm not able to upload files, just view directories.
Have you receive such problem with other services that use HDFS?
Do the Pipeline.IO have some kind of tools, for uploading data files into HDFS through webbrowser?

**Comment by cfregly** [comment]
@Hronom I'm working on integrating hue into the system.  at that point, everything will be sharing the same Kubernetes-based DNS which will make things much easier to configure.

here is the start of my work:  

https://github.com/fluxcapacitor/pipeline/commit/d037c7773ba1d1ca93a31d4bfa3ef1b224b26043

feel free to finish it off if you'd like.  otherwise, i'll try to get to it over the next few days
i like the HDFS file upload support.  pretty cool!

-chris

**Comment by Hronom** [comment]
@cfregly Very cool!
Also HUE have other cool features, like: Metastore, ZooKeeper nodes browsing etc.

As far as I see you start to integrate it in the image with HDFS, so I think you will not have problem with resolving by hostname. Because I'm run it as separate Service...

**Comment by cfregly** [comment]
yup, i saw the other features of hue.  fits very nicely into the stack.

for now, hue is packaged with hdfs for convenience and rapid testing.  it will definitelywork with other services living in other pods/containers such as zookeeper, etc.

all of pipeline.io is distributed - and this will be no exception.  temporary home while we prove out this tool.

more coming soon!  great idea, @hronom!

**Comment by Hronom** [comment]
@cfregly So you're planning to embed it in each image, I mean zookeeper will have own HUE installation?
Or it's just temp solution for testing?

**Comment by cfregly** [comment]
it will be exactly as you expect - and similar to every other service in the pipeline.io stack.

hue will be setup in a single image/container/pod/service running anywhere on the cluster, but able to communicate with every other service running within the cluster.

hold tight.  this will come together very soon!  :)

**Comment by cfregly** [comment]
@Hronom we've been focused on the model deployment and serving later this past month.

or are you still waiting on us?  if you've made any progress, we'd love a pull request!

**Comment by cfregly** [comment]
closing this for now.  please re-open HUE-specific issue for separate tracking.
