### ISSUE TITLE
Document best practices for Airflow

### ISSUE THREAD

**Issue by cfregly** [fluxcapacitor/pipeline#203]
specifically, answer these common questions:

How do i create and deploy a spark job?

How do i create and deploy a TensorFlow job?

Where should I put the source code for the jobs (both airflow dag and spark/tensorflow)?

How do i trigger the airflow dag upon github commit?

**Comment by uover82** [comment]
good questions/ flows to consider :-)

**Comment by Hronom** [comment]
Me too

**Comment by Hronom** [comment]
How to add DAG, can you please guide me to the right way?

**Comment by Hronom** [comment]
As far as I'm understanding, right now I'm only able to upload files through copy to the container?

**Comment by cfregly** [comment]
@Hronom correct. and i just spoke with one of the airflow committers.  he confirmed that editable airflow DAGs are not on the near-term roadmap.

stability and scale are their primary concerns at the moment - which is a good thing, of course! 

closing this for now as an adequate workaround exists.
