### ISSUE TITLE
Spark 2.1.0 is not supported with Zeppelin-0.7.0-SNAPSHOT

### ISSUE THREAD

**Issue by zxsimple** [fluxcapacitor/pipeline#214]
I get the latest Zeppelin docker image and Spark-2.1.0 image, when I tried to run spark code it displays "Spark 2.1.0 is not supported".

echo $SPARK_VERSION get 2.1.0.

**Comment by cfregly** [comment]
@BrentDorsey : can you look into this?

@zxsimple : which Docker image did you pull?  which tag/version, exactly?

**Comment by zxsimple** [comment]
fluxcapacitor/zeppelin:latest, I pulled it this morning
fluxcapacitor/spark-master-2-1-0
fluxcapacitor/spark-worker-2-1-0

the spark image I pulled 4 days ago, I see it is the exactly the same size as I pulled this morning.

**Comment by cfregly** [comment]
ok i'll work with brent in the morning to track this down.

we've been doing a lot of refactoring - and at the same time a lot of versioning, adding more continuous builds; etc.  likely there's a version mismatch.

can you try to pull the :v1.0.0 tag from docker hub?

ie docker pull fluxcapacitor/spark-master-2-1-0:v1.0.0

**Comment by cfregly** [comment]
there is no more "latest" tag.  this is on purpose.

only "master" and "v1.0.0"

**Comment by zxsimple** [comment]
I consider it related to Zeppelin rather than Spark, I'll update the both the images with tag v1.0.0 and see.

**Comment by zxsimple** [comment]
Without luck, still report the issue. 
I checked the code of Zeppelin, checking of Spark version defined in org.apache.zeppelin.spark. SparkVersion. There should be no problem of the code.

`  public boolean isUnsupportedVersion() {
    return olderThan(MIN_SUPPORTED_VERSION) || newerThanEquals(UNSUPPORTED_FUTURE_VERSION);
  }`

The code change was made on Jan 4, 2017 for Spark version upgrade from 2.0.0 to 2.1.0, I see the Docker image is Zeppelin-0.7.0-SNAPSHOT, does that build before the change?

**Comment by cfregly** [comment]
we're looking into this @zxsimple

**Comment by BrentDorsey** [comment]
@cfregly<https://github.com/cfregly> : I don’t have access to code that was used to build 0.7.0-spark-2.0-scala-2.11-SNAPSHOT<https://github.com/fluxcapacitor/pipeline/blob/master/zeppelin.ml/Dockerfile#L12>.

pipeline/zeppelin.ml/Dockerfile<https://github.com/fluxcapacitor/pipeline/blob/master/zeppelin.ml/Dockerfile#L6> uses https://s3.amazonaws.com/fluxcapacitor.com/packages/zeppelin-0.7.0-spark-2.0-scala-2.11-SNAPSHOT but there’s no zeppelin directory in package.ml<https://github.com/fluxcapacitor/pipeline/tree/master/package.ml>

Can you share the code you used to build 0.7.0-spark-2.0-scala-2.11-SNAPSHOT?

If not I can add a new Zeppelin build in package.ml<https://github.com/fluxcapacitor/pipeline/tree/master/package.ml>.

I was in the process of adding a Zeppelin build the other day but stopped when I noticed the new fluxcapacitor 0.7.0-spark-2.0-scala-2.11-SNAPSHOT build assuming you beat me to it.

**Comment by cfregly** [comment]
@BrentDorsey can you add your build?

mine is from a long time ago.  the version # is misleading.  

i've been waiting for you to add your newer version.

lemme know when it's in master and i'll merge it into the r1.0 branch, as well.

**Comment by BrentDorsey** [comment]
Yes sir, I should be able to get to it this evening.

**Comment by BrentDorsey** [comment]
Zeppelin
- updated dockerfile to use archive 0.8.0-SNAPSHOT
- updated replication controller from spark_master_2_0_1 to 2_1_0

@cfregly - zeppelin docker image in fluxcapacitor docker hub needs to be updated.

**Comment by cfregly** [comment]
merged into master, built/pushed docker image to dockerhub: https://hub.docker.com/r/fluxcapacitor/zeppelin/

**Comment by zxsimple** [comment]
I pulled the image found the $ZEPPELIN_HOME is zepellin-0.8.0-spark-2.1-scala-2.11-SNAPSHOT, however it is empty except the conf/ folder, the process ZeppelinServer also not started. So I changed the $ZEPPELIN_HOME to be zeppelin-0.8.0-SNAPSHOT and started the process manually.

Can you please see this?

**Comment by cfregly** [comment]
@zxsimple ok, i know what's going on.  i need to change the .tar.gz bundle that @BrentDorsey created to point to the longer name 'zeppelin-0.8.0-spark-2.1-scala-2.11-SNAPSHOT'.

the end result will be the zeppelin-0.8.0-spark-2.1-scala-2.11-SNAPSHOT/bin, /conf, etc. with everything under the long name.

this should be done soon.   i'll update when it's done.

**Comment by cfregly** [comment]
@zxsimple ok, the docker images (v1.0.0 and master) have been updated.
