### ISSUE TITLE
initial setup missing required predict-pmml endpoint

### ISSUE THREAD

**Issue by adrinjalali** [fluxcapacitor/pipeline#223]
After an initial setup of the system, i.e. after [this](https://github.com/fluxcapacitor/pipeline/wiki/Setup-Pipeline-on-Kubernetes), I started trying [this file](https://github.com/fluxcapacitor/pipeline/blob/master/jupyterhub.ml/notebooks/scikit-learn/Deploy_Scikit_Learn_Iris_DecisionTree.ipynb) which tries to talk to the `predict-pmml` service in two sections, using these links:

    update_url = "http://<your-ip>:39040/update-pmml/pmml_iris"
    evaluate_url = 'http://<your-ip>:39040/evaluate-pmml/pmml_iris'

But at least form this file, it is not clear what those IP addresses are, which services they belong to, and how to find them.

Even if we assume they refer to the `predict-pmml` service, that service for me is shown as bellow:

```
# kubectl describe svc prediction-pmml
Name:			prediction-pmml
Namespace:		default
Labels:			hystrix.enabled=true
Selector:		hystrix.enabled=true,name=prediction-pmml
Type:			LoadBalancer
IP:			x.x.x.x
LoadBalancer Ingress:	blahblah.eu-central-1.elb.amazonaws.com
Port:			prediction-pmml	 80/TCP
NodePort:		prediction-pmml 31173/TCP
Endpoints:		y.y.y.y:9040
Session Affinity:	None
No events.
```
I tried different addresses: 
- `blahblah.eu-central-1.elb.amazonaws.com:80` => `HTTPError: HTTP Error 405: Method Not Allowed`
- `x.x.x.x` => `HTTPError: HTTP Error 405: Method Not Allowed`
- `y.y.y.y:9040` => `HTTPError: HTTP Error 405: Method Not Allowed`
- `blahblah.eu-central-1.elb.amazonaws.com:31173` => `URLError: <urlopen error timed out>`
- `x.x.x.x:31173` => `URLError: <urlopen error timed out>`
- `y.y.y.y:39040` => `URLError: <urlopen error [Errno 111] Connection refused>`

Is there anything I should've done that I haven't? Or is it a documentation/implementation bug?

**Comment by cfregly** [comment]
@adrinjalali 

the notebook you referenced is from an old demo that used different ports than normal.  apologize for the confusion.  we need to add more documentation, for sure.  we're actively working on this right now.

in the meantime, here's a more recent notebook that has the latest URLs:  

https://github.com/fluxcapacitor/source.ml/blob/master/jupyterhub.ml/notebooks/talks/GlobalDataScience/Mar272017-SantaClara-Deploy-SparkML-TensorflowAI/GlobalDataScience-SparkMLTensorflowAI-HybridCloud-ContinuousDeployment.ipynb

i just did this talk yesterday, so it should be up to date!  :)

also, i wanted to point out that the jupyterhub.ml/notebooks folder should (and will be right after i send this comment) removed.

we've decoupled most source code and notebooks into a separate repo [here](https://github.com/fluxcapacitor/source.ml).  we did this to make it easier for users of PipelineIO to use their own source repos - while still reusing the PipelineIO runtime.

i realize this is a bit confusing, as well.  doing our best to document this stuff.

thanks for pointing this out.  hopefully, that helps.  please re-open if you need more info.
