### ISSUE TITLE
Run the Docker Container using the Loaded Image

### ISSUE THREAD

**Issue by rkulan007** [fluxcapacitor/pipeline#23]
When the below command is run, getting "docker: Error response from daemon: client is newer than server (client API version: 1.22, server API version: 1.20)." error.

Appreciate your assistance.

docker run -i --privileged --name pipeline -h docker -m 8g -p 80:80 -p 36042:6042 -p 39160:9160 -p 39042:9042 -p 39200:9200 -p 37077:7077 -p 38080:38080 -p 38081:38081 -p 36060:6060  -p 36061:6061 -p 36062:6062 -p 36063:6063 -p 36064:6064 -p 36065:6065 -p 32181:2181 -p 38090:8090 -p 30000:10000 -p 30070:50070 -p 30090:50090 -p 39092:9092 -p 36066:6066 -p 39000:9000 -p 39999:19999 -p 36081:6081 -p 35601:5601 -p 37979:7979 -p 38989:8989 -p 34040:4040 -p 34041:4041 -p 34042:4042 -p 34043:4043 -p 34044:4044 -p 34045:4045 -p 34046:4046 -p 34047:4047 -p 34048:4048 -p 34049:4049 -p 34050:4050 -p 34051:4051 -p 34052:4052 -p 34053:4053 -p 34054:4054 -p 34055:4055 -p 34056:4056 -p 34057:4057 -p 34058:4058 -p 34059:4059 -p 34060:4060 -p 36379:6379 -p 38888:8888 -p 34321:54321 -p 38099:8099 -p 38754:8754 -p 37379:7379 -p 36969:6969 -p 36970:6970 -p 36971:6971 -p 36972:6972 -p 36973:6973 -p 36974:6974 -p 36975:6975 -p 36976:6976 -p 36977:6977 -p 36978:6978 -p 36979:6979 -p 36980:6980 -p 35050:5050 -p 35060:5060 -p 37060:7060 fluxcapacitor/pipeline bash

**Comment by cfregly** [comment]
hey @rkulan007!

thanks for trying out fluxcapacitor!

i googled for your error and found the following:  https://github.com/docker/machine/issues/2147

might want to try a `docker-machine upgrade`, maybe?  this is more of a docker issue than a fluxcapacitor issue, but i will help you as best i can as others may experience similar issues.

can you google around a bit and post the version of docker-machine that you're using, etc?

thanks!

**Comment by rkulan007** [comment]
Hi Chris,

Thanks for the prompt reply.
I reinstalled the pipeline VM and tried again with upgrade, no luck.

$ docker-machine create --driver virtualbox --virtualbox-hostonly-cidr "192.69.69.1/24" --virtualbox-cpu-count "8" --virtualbox-disk-size "100000" --virtualbox-memory "8096" pipeline-vm
Running pre-create checks...
Creating machine...
(pipeline-vm) Copying C:\Users\vel\.docker\machine\cache\boot2docker.iso to C:\Users\vel\.docker\machine\machines\pipeline-vm\boot2docker.iso...
(pipeline-vm) Creating VirtualBox VM...
(pipeline-vm) Creating SSH key...
(pipeline-vm) Starting the VM...
(pipeline-vm) Check network to re-create if needed...
(pipeline-vm) Waiting for an IP...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with boot2docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: D:\Vel\Apps\Docker Toolbox\docker-machine.exe env pipeline-vm

$ docker-machine ls
NAME          ACTIVE   DRIVER       STATE     URL                        SWARM   DOCKER    ERRORS
pipeline-vm   -        virtualbox   Running   tcp://192.69.69.101:2376           v1.10.3

$ docker-machine upgrade pipeline-vm
Waiting for SSH to be available...
Detecting the provisioner...
Upgrading docker...
Stopping machine to do the upgrade...
Upgrading machine "pipeline-vm"...
Copying C:\Users\vel\.docker\machine\cache\boot2docker.iso to C:\Users\vel\.docker\machine\machines\pipeline-vm\boot2docker.iso...
Starting machine back up...
(pipeline-vm) Check network to re-create if needed...
(pipeline-vm) Waiting for an IP...
Restarting docker...

$ docker ps
Error response from daemon: client is newer than server (client API version: 1.22, server API version: 1.20)


Regards
Kulan

**Comment by cfregly** [comment]
@rkulan007 have you made any progress?

couple more questions:  
1) have you ever installed docker on this machine before?
2) can you do a `which docker` and post the output?
3) i assume you're using windows - which i don't much experience with, unfortunately, but i know it's being used by a LOT of people!

we'll need to keep googling and trying things out.  please let me know if you find anything.  and i'll do the same.  i have parallels on my mac, so i can try to follow the instructions and see what happens on my end.

**Comment by cfregly** [comment]
@rkulan007 there is some new info here that may be helpful:

http://stackoverflow.com/questions/24586573/docker-error-client-and-server-dont-have-same-version/36298911#36298911

**Comment by cfregly** [comment]
closing for now.  please reopen if you're still having an issue.

thanks!
