### ISSUE TITLE
Visualization for machine learning models.

### ISSUE THREAD

**Issue by AIAdventures** [fluxcapacitor/pipeline#237]
awesome youtube presentation! Are you going to integrate visualisation, streaming dashboard, online model diagnosis?
Many thanks,
Best,
Andrew﻿

**Comment by cfregly** [comment]
@AIAdventures we have everything you're asking for!

Here's a link to the documentation including screen shots of our visualizations, dashboards, and model diagnostics.

PipelineIO was built on a metrics-first approach.  everything you push to production with PipeilneIO is monitored with as much insight as possible.

Furthermore, every model is auto-scalable, fault-tolerant across hybrid-cloud and on-premise, and fronted by circuit breakers which will automatically return a suitable fallback if the service is down - or cannot fulfill the given SLAs.

Insight and adaptable are native features of the PipelineIO platform.

**Comment by cfregly** [comment]
http://pipeline.io/model_monitor/
