### ISSUE TITLE
Lock down airflow with username/password - or, better yet, oauth support

### ISSUE THREAD

**Issue by cfregly** [fluxcapacitor/pipeline#239]

**Comment by datascienceit** [comment]
Airflow security #240 

A. Change to NodePort to apply the need for SSH-tunnel.
B. Added the config to set a user and password.

To set the user+password you can use this instructions:
`https://airflow.incubator.apache.org/security.html`

I also added a script which makes it simple to run, but I can't manage to push it to source.ml, so you can find it on your email. 
Just add it to source.ml/scheduel.ml/airflow, and then you can run this line to set a user\password\email:
```
kubectl exec -it $(kubectl get pods \
    --selector=app=scheduler-airflow -o \
    jsonpath={.items..metadata.name}) \
            python /root/volumes/source.ml/scheduler.ml/airflow/airflow-security.py \
            <your-name> <your-password> <your-email>

```
