### ISSUE TITLE
List minimum specs for creating docker containers  

### ISSUE THREAD

**Issue by scanlonjts** [fluxcapacitor/pipeline#24]
even though in the docker machine commands and docker commands it is clear that min 8G is required for image should state that up front (would have told me I needed to run from 16G MBP rather than day to day 8G MBA)

**Comment by cfregly** [comment]
@scanlonjts what types of issues were you seeing?

i run with 8 GB from time to time and, while not the snappiest, it's not dead in the water.

perhaps i've added something recently that is causing problems.  gimme some more deets - and i'll do some testing on my end.

there is definitely a slimmer profile that i can default to.  by default - and for demo purposes - i'm starting every service.  this is definitely not required, however.

we'll get it running for ya.

**Comment by scanlonjts** [comment]
i was actually just doing the initial docker provisioning and my machine went into meltdown mode - MacBookAir - 8G all SSD - when VBox pushes too hard it goes into meltdown (I will setup on my other machine)

**Comment by cfregly** [comment]
here's instructions on how to use a cloud instance like EC2:  

https://github.com/fluxcapacitor/pipeline/wiki/Cloud-Provisioning

this should get you further, anyway.  :)
