### ISSUE TITLE
Installation on existing kubernetes cluster

### ISSUE THREAD

**Issue by adrianog** [fluxcapacitor/pipeline#241]
The documentation seems to reference either Cloud Providers or MiniKube. With no mentions of "just" a Kubernetes Cluster.

Can we just follow the instructions for MiniKube and/or the Cloud Providers?

This page is very confusing https://github.com/fluxcapacitor/pipeline/wiki/Setup-Pipeline-Mini (Step 1, 2, 3 on this page, plus the Step 1, 2 in the menu on the right....).

[Thank you for the interesting components]

**Comment by adrianog** [comment]
Perusing further reveals that I can probably just follow https://github.com/fluxcapacitor/pipeline/wiki/Setup-Pipeline-on-Kubernetes - and substitute any reference to a Cloud Provider K8s cluster, with a reference to my locally running cluster. I don't see anything vendor specific on that page, which is good sign.

**Comment by cfregly** [comment]
@adrianog yup, all of that is open source.  i was pressured by friends and family to create a better website for PipelineIO.  this is why you may find some links in Github that link to http://pipeline.io and back.  

we are certainly working on value add extensions so we can pay the AWS bill each month, but the core is all open source.  :)
