### ISSUE TITLE
Build guild project failed

### ISSUE THREAD

**Issue by zxsimple** [fluxcapacitor/pipeline#257]
This is Sanders, I got trouble in building guild project, I saw you also submitted related issue in guild project. Once you fix that, would you please update the Dockerfile?

Initially I got check sum mismatch issue as following:
```
ERROR: error loading package '': Encountered error while reading extension file 'closure/defs.bzl': no such package '@io_bazel_rules_closure//closure': Error downloading [http://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/4c559574447f90751f05155faba4f3344668f666.tar.gz, https://github.com/bazelbuild/rules_closure/archive/4c559574447f90751f05155faba4f3344668f666.tar.gz] to /root/.cache/bazel/_bazel_root/cc96cea90b54a4936c65c34f3306c63b/external/io_bazel_rules_closure/4c559574447f90751f05155faba4f3344668f666.tar.gz: Checksum was 2b43d9b683ba8c34811b31cc4afebbce3cf3beae528fc678bb37e23054942b8a but wanted e9e2538b1f7f27de73fa2914b7d2cb1ce2ac01d1abe8390cfe51fb2558ef8b27
```

Then I made some code change to Dockerfile for temporary fix like this:
```
# Guild
RUN \
  git clone https://github.com/guildai/guild-python.git \
  && cd guild-python \
  # Temporary fix check sum mismatch issue
  && sed -i 's/9379e711f71c5ba537f047edb60bb2eaca268f75425cd0dd16e3aba48907f2a0/01882d640f205e4872da04d127e2014cfb342097eb1c22bc52af8bbb53e0d06b/g' WORKSPACE \
  && sed -i '19,20d' third-party/psutil.BUILD \
  && sed -i '43,53d' components/guild-imports/BUILD \
  && sed -i '82,91d' components/guild-imports/BUILD \
  && sed -i '13d' components/guild-components-page/BUILD \
  && sed -i '17d' components/guild-components-page/guild-components-page.html \
  && sed -i '14d' components/guild-keyval-compare-component/BUILD \
  && bazel build guild --verbose_failures
```  

Unfortunately, build still fails.
<img width="1280" alt="2017-09-26 2 07 38" src="https://user-images.githubusercontent.com/10580990/30845280-4d9d3196-a258-11e7-91a3-7a5422c008ce.png">

Thanks for your help!

**Comment by cfregly** [comment]
hey sanders!

the guild-python stuff is a different project - and it's under construction from what i hear.  you  might want to file an issue here:  https://github.com/guildai/guild-python

the project owner is very responsive.

that said, we actually have an older version that works well on TensorFlow 1.2.  i'll share that repo with you soon.

**Comment by cfregly** [comment]
https://github.com/PipelineAI/train

**Comment by zxsimple** [comment]
Thank you so much !!
