### ISSUE TITLE
Setup the Environment: bug on path

### ISSUE THREAD

**Issue by dalvarom** [fluxcapacitor/pipeline#27]
On the setup The Environment page, you say that we should launch the following command. 
root@docker$ ~/pipeline/bin/initial/RUNME_ONCE.sh
Instead of the previous command, the correct one is
root@docker$ ~/pipeline/bin/RUNME_ONCE.sh

By the way, thank you for your example.

**Comment by cfregly** [comment]
@dalvarom hey there!

good catch.  you caught us in that rare moment where the wiki docs were updated BEFORE the PR was merged!

in other words, if you do a `git pull` right now, you would find that script in `bin/initial`.

thanks again for keeping us honest.  :)
