### ISSUE TITLE
Port assignment in pipeline-pyspark.sh for 8754

### ISSUE THREAD

**Issue by stephlocke** [fluxcapacitor/pipeline#28]
Working through the instruction wiki - using only the code provided -  when I try running `pipeline-pyspark.sh` or `pyspark.sh` I get the following:

```
[W 15:23:11.420 NotebookApp] server_extensions is deprecated, use nbserver_extensions
/usr/local/lib/python2.7/dist-packages/widgetsnbextension/__init__.py:30: UserWarning: To use the jupyter-js-widgets nbextension, you'll need to update
    the Jupyter notebook to version 4.2 or later.
  the Jupyter notebook to version 4.2 or later.""")
[W 15:23:11.476 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[W 15:23:11.476 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using authentication. This is highly insecure and not recommended.
[I 15:23:11.477 NotebookApp] The port 8754 is already in use, trying another port.
[C 15:23:11.477 NotebookApp] ERROR: the notebook server could not be started because no available port could be found.
```

Running
```
lsof -Pnl +M -i4
```
I get that jupyter should be using 8754
```
jupyter-n 2541        0    3u  IPv4  30881      0t0  TCP *:8754 (LISTEN)
```

Trying to then call `pyspark` still gets the port error.

Am I missing something that I should have done?

**Comment by cfregly** [comment]
hey there, steph!

can you send me a link to the exact setup instructions that you followed?  are you running this on a fresh cloud instance or a local laptop environment.

obviously, if something else is already running on port 8754, you would need to either kill that process or update the port in the $PIPELINE_HOME/config/jupyter/jupyter_notebook_config.py file:

https://github.com/fluxcapacitor/pipeline/blob/master/config/jupyter/jupyter_notebook_config.py

and what do you mean by "using only the code provided"?

it might be easier to take this offline by sending an email to help@fluxcapacitor.com.

thanks!

-chris

**Comment by cfregly** [comment]
ah, i think i see the issue, steph.  let me try to come up with a fix.  

in the mean time, can you use the jupyter/ipython notebook?

**Comment by cfregly** [comment]
the quick fix is to set the following exports then run `pyspark`

```
export PYSPARK_DRIVER_PYTHON=""
export PYSPARK_DRIVER_PYTHON_OPTS=""
```

**Comment by cfregly** [comment]
only setting the following for the jupyter notebook process as service startup time:

PYSPARK_DRIVER_PYTHON="jupyter" PYSPARK_DRIVER_PYTHON_OPTS="notebook -- config=$CONFIG_HOME/jupyter/jupyter_notebook_config.py" ...
