### ISSUE TITLE
[Demo] HTML-based Image classification using TensorFlow using image_url query param

### ISSUE THREAD

**Issue by cfregly** [fluxcapacitor/pipeline#68]

**Comment by cfregly** [comment]
@andyzeli can you take a look at this?  i can provide more info when we speak next.  we can summarize everything here after our talk.

**Comment by cfregly** [comment]
@andyzeli:  let's discuss this and take notes together.  i've already started this - i just need you to add the final touches including production-hardening and metrics around this feature.

**Comment by andyzeli** [comment]
https://github.com/fluxcapacitor/pipeline/tree/master/myapps/serving/tensorflow

^^^ this is what you go started, correct?

**Comment by cfregly** [comment]
yup, here's the exact flask-based python app:  

https://github.com/fluxcapacitor/pipeline/blob/master/myapps/serving/tensorflow/tensorflow-inception-serving-service-proxy.py#L11

You'll see a TODO in there to retrieve the 

The goal is to be able to make a REST call as follows:

```
http://<ip>:5070/classify?url=https://static01.nyt.com/images/2007/04/02/us/02mormon.600.jpg
```

where the service downloads the image locally, puts it in a /tmp path on the server, calls tensorflow to classify the image, then returns the classes with their probabilities as follows:

```
{
	"results": ["9.624312 : giant panda, panda, panda bear, coon bear, Ailuropoda melanoleuca\n", "6.466392 : indri, indris, Indri indri, Indri brevicaudatus\n", "4.079736 : lesser panda, red panda, panda, bear cat, cat bear, Ailurus fulgens\n", "3.872451 : gibbon, Hylobates lar\n", "2.635539 : titi, titi monkey\n"],
	"retval": 0
}
```

**Comment by cfregly** [comment]
long-term, we're replacing this python service with a JVM-based NetflixOSS connector to allow TensorFlow to participate in the NetflixOSS infrastructure (service discovery, load balancing, etc).

here's the issue tracking this effort:  https://github.com/fluxcapacitor/pipeline/issues/66

here's the start of this "sidecar" integration of NetflixOSS (JVM-based) + TensorFlow (C-based):  https://github.com/fluxcapacitor/pipeline/tree/master/myapps/serving/tensorflow/src/main

ideally, we'll call into TensorFlow directly using JavaCPP or equivalent.
