### ISSUE TITLE
Support Theano and Caffe deployment runtimes

### ISSUE THREAD

**Issue by cfregly** [fluxcapacitor/pipeline#80]

**Comment by westover** [comment]
Would be interested to see the Caffe runtimes

**Comment by cfregly** [comment]
@westover hey there!

any chance you could put together a Dockerfile that would contain your ideal Caffe runtime?  we've got Theano somewhat integrated, but not yet a true first-class citizen.

any help to jump start the Caffe effort would be much appreciated!

**Comment by cfregly** [comment]
focusing on tensorflow for now
