### ISSUE TITLE
Compare Spring/NetflixOSS-based Microservices to Lightbend Lagom along various dimensions

### ISSUE THREAD

**Issue by cfregly** [fluxcapacitor/pipeline#95]
performance, dynamic deployment, metrics, chaos monkey/failover, autoscaling up/down, canary analysis (existing models to new model canary), rollback, green/blue deployments, request batching/collapsing, etc

**Comment by andyzeli** [comment]
https://www.lightbend.com/activator/templates#filter:lagom

some seed projects to get a head start may be useful

**Comment by andyzeli** [comment]
pretty good explanation by Jamie Allen about Lagom's Raison d'etre. good overview before exploring deeply

**Comment by cfregly** [comment]
good stuff.  i know @jamie-allen very well.  great speaker.

talked with @deanwampler yesterday (another great speaker) about Lagom, Conductor, etc - thanks to a suggestion by @agibsonccc who is exploring Lagom and Conductor for DL4J integration. 

Lagom is definitely something we should be reviewing - at a minimum for the patterns that it highlights.  

sounds like Lightbend is not specifically focused on combining Lagom + ML + Streaming at the moment, but this is an area of integration that some of their teams have been exploring - including integration with flink streaming.

Working with @jgrier from data artisans on serving Spark ML with Flink Streaming.  This work is being tracked here:  https://github.com/fluxcapacitor/pipeline/issues/113

**Comment by agibsonccc** [comment]
Lagom is my defacto choice for a lot of reasons. A big one being the pluggable service locators:
https://github.com/jboner/lagom-service-locator-zookeeper
https://github.com/jboner/lagom-service-locator-consul

Another one is the first class integration with most of the SMACK stack already.
Both are play based.

I also like how they are prioritizing cassandra kafka etc.

The spring guys are doing some cool stuff with dl4j though:
http://www.slideshare.net/javafxpert/machine-learning-exposed

**Comment by cfregly** [comment]
More on the Pivotal + DL4J Nueral Network Visualizer (and Prediction REST Service) that @agibsonccc referenced in the slideshare above:

https://github.com/JavaFXpert/visual-neural-net-server
https://github.com/JavaFXpert/ng2-spring-websocket-client

**Comment by agibsonccc** [comment]
Haha didn't want to spam it too much. My main point is that dl4j is very
much targeting the microservices crowd and it seems to be resonating.
I'm sure we'll see more stuff like that.

**Comment by cfregly** [comment]
closing this
